# Site settings
title: Boa
description: >
  The blog and website for Boa
baseurl: "" # should be / if you build a global github page (eg o0ignition0o.github.io)
url: "127.0.0.1:4000" # The blog url you want to choose (you can use a github.io one, or pick your own hosted url :))
logo: "/images/logo.png" # This one is used as blog logo
# twitter_username: o0ignition0o # Your twitter handle
# github_username: o0Ignition0o # Your github handle

# Build settings
highlighter: rouge

root: "https://boa-dev.github.io" # Not really sure this is useful, need to cross check with blog writers :)
